---
apiVersion: v1
kind: Service
metadata:
  name: stefcat-test-service
  labels:
    username: stefcat
    env: test
spec:
  type: ClusterIP
  selector:
    app: stefcat-test-redis
  ports:
  - name: stefcat-test-redis
    port: 6379
    targetPort: 6379

