---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stefcat-test-pvc
  labels:
    username: stefcat
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi

